import "bootstrap/dist/css/bootstrap.min.css";
import "react-loading-skeleton/dist/skeleton.css";
import vazirFont from "@/constants/localFont";
import "./globals.scss";
import { headers } from "next/headers";
import { Header } from "@/components/header/index";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children, params }) {
  const headersList = await headers();
  const locale = headersList.get("x-next-i18n-router-locale");

  return (
    <html lang={locale} dir="auto">
      <body className={`min-vh-100  ${vazirFont.variable} font-sans `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
export default RootLayout;
