import "bootstrap/dist/css/bootstrap.min.css";
import vazirFont from "@/constants/localFont";
import "./globals.scss";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`min-h-screen  ${vazirFont.variable} font-sans `}>
        {children}
      </body>
    </html>
  );
}
