import "bootstrap/dist/css/bootstrap.min.css";
import vazirFont from "@/constants/localFont";
import "./globals.scss";
import { headers } from "next/headers";
import { infoLang } from "@/lib/i18n/infoLang";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children }) {
   const headersList = await headers();
  const locale = headersList.get('x-next-i18n-router-locale');

  return (
    <html lang={locale} dir={infoLang[locale].dir}>
      <body className={`min-vh-100  ${vazirFont.variable} font-sans `}>
        {children}
      </body>
    </html>
  );
}
export default RootLayout;
